<?php
    $configs = $block->getConfigs();
    $alignment = $configs['autocomplete']['menu']['alignment'];
    $noResultsText = $configs['autocomplete']['menu']['noResultsText'];
?>

<script type="text/template" id="wizzy-autocomplete-wrapper">
    <div class="wizzy-autocomplete-wrapper
    <?php if ($alignment == "right") { ?> onRight <?php } else { ?> onLeft <?php } ?>
    {{^topProducts}}withoutTopProducts{{/topProducts}}"
         style="display: {{^isMenuHidden}}flex{{/isMenuHidden}}">
    {{#topProducts}}
            {{{topProducts}}}
        {{/topProducts}}
        {{#suggestions}}
            {{{suggestions}}}
        {{/suggestions}}
        {{^suggestions}}
            {{^topProducts}}
                <div class="autocomplete-no-results">
                    <p><?= $block->escapeHtmlAttr($noResultsText); ?></p>
                </div>
            {{/topProducts}}
        {{/suggestions}}
    </div><!-- ending of wizzy-autocomplete-wrapper -->
</script>