<?php
/** @var $block \Magento\Framework\View\Element\Template */
$configs = $block->getConfigs();
$currency = $configs['store']['currency']['symbol'];
?>

<script type="text/template" id="wizzy-search-results-product">

    <li class="wizzy-result-product wizzy-product-{{id}}
        {{#groupId}}has-variations wizzy-group-product-{{groupId}}{{/groupId}}"
            title="{{{ name }}}" data-id="{{id}}" {{#groupId}}data-groupId="{{groupId}}"{{/groupId}}>

      <span class="wizzy-product-variation-loader-bg"></span>
      <span class="wizzy-product-variation-loader"></span>

      <a href="{{{url}}}" class="wizzy-result-product-item">
         <div class="result-product-item-image">
            <img src="{{ mainImage }}" class="product-item-image" />
         </div><!-- ending of result-product-item-image -->
         <div class="result-product-item-info">
            <p class="product-item-title">{{{ name }}}</p>
            {{#subTitle}}
            <p class="product-item-sub-title">{{{subTitle}}}</p>
            {{/subTitle}}
            {{#swatches}}
             <div class="product-item-swatch-group
             {{#isPrimary}}swatch-group-primary{{/isPrimary}} swatch-group-{{key}}"
                  data-swatchKey="{{key}}">
               {{#values}}
                 <div data-variationId="{{variationId}}" title="{{#value}}{{value}}{{/value}}"
                      class="product-item-swatch-item
                      {{#isSelected}}swatch-selected{{/isSelected}}
                      {{#inStock}}swatch-in-stock{{/inStock}}">
                    <?= $block->getReusableHTML('Wizzy_Search::common/swatch.phtml'); ?>
               </div>
               {{/values}}
            </div><!-- ending of product-item-swatch-group -->
            {{/swatches}}
            <div class="wizzy-product-item-price-reviews-wrapper">

               <div class="wizzy-product-item-reviews">
                  {{#avgRatings}}
                   <span class="product-item-reviews-avgRatings">{{avgRatings}}</span><span
                           class="product-item-review-wrapper">&#x2605;</span>{{#totalReviews}}<span
                           class="product-item-reviews-totalReviews">({{totalReviews}})</span>{{/
                   totalReviews}}
                  {{/avgRatings}}
               </div>

               <div class="wizzy-product-item-price {{#hasSwatches}}with-swatches{{/hasSwatches}}">
                    <?= $block->escapeHtmlAttr($currency); ?>{{ sellingPrice }}
                  {{#price}}
                  <br>
                  <span class="product-item-original-price">
                                    <?= $block->escapeHtmlAttr($currency); ?>{{ price }}
                               </span>
                  <span class="product-item-discount">
                                   {{#discountPercentage}}
                                       ({{discountPercentage}}% off)
                                   {{/discountPercentage}}
                               </span>
                  {{/price}}
               </div>
            </div>
         </div><!-- ending of result-product-item-info -->
      </a><!-- ending of wizzy-result-product-item -->
   </li><!-- ending of wizzy-result-product -->

</script>