<?php
$configs = $block->getConfigs();
?>

<script type="text/template" id="wizzy-search-sort">

   <div class="wizzy-sort-container" {{#hasToDisplayFiltersAtTop}} style="top:{{filtersButtonOffset}}px"
      {{/hasToDisplayFiltersAtTop}}>
       <select class="wizzy-sort-select" id="wizzy-sort-select">
         {{#options}}
            <option value="{{ field }}"
                    data-order="{{order}}"
                    {{#isSelected}}selected{{/isSelected}}>
           {{ label }}
           </option>
         {{/options}}
      </select>
      {{#displayTileView}}
         <div class="wizzy-tile-view-icon">
               <button class="wizzy-tile-view-button" aria-label="Zoom in and out" data-value="4">
               {{#tileViewConfig}}
               <div class="wizzy-tile-view-icon-grid {{#isActive}} wizzy-filled-grid {{/isActive}}"></div>
               {{/tileViewConfig}} 
               </button>
         </div>
     {{/displayTileView}}
   </div>

</script>