<script type="text/template" id="wizzy-facet-category-item">
    <li class="wizzy-facet-list-item facet-category-hierarchy-item {{#isSelected}}active{{/isSelected}}" data-key="{{ key }}" data-term="{{{ label }}}" title="{{{ label }}}">
          <span class="wizzy-facet-list-item-label">
             <span class="wizzy-facet-list-item-checkbox">
                    <input type="checkbox" {{#isSelected}}checked{{/isSelected}} />
                    <div class="checkbox-indicator"></div>
             </span>
             {{{ label }}}
          </span>
          <span class="wizzy-facet-list-item-count">
             ({{ count }})
          </span>

          {{#childrenHTML}}
                <ul class="wizzy-facet-list facet-child-list">
                    {{{childrenHTML}}}
                </ul>
          {{/childrenHTML}}
    </li>
</script>