<?php
$configs = $block->getConfigs();
?>
<script type="text/template" id="wizzy-selected-facet-item-common">
    <li class="wizzy-selected-facet-list-item {{#isSwatch}}facet-has-swatch{{/isSwatch}}" data-facetKey="{{facetKey}}"
        data-key="{{ key }}" data-term="{{{ label }}}" title="{{{ label }}}">
      <span class="wizzy-selected-facet-list-item-label">
            <?= $block->getReusableHTML('Wizzy_Search::common/swatch.phtml'); ?>
        <span class="facet-item-label-value">{{{ label }}}</span>
      </span>
      <span class="wizzy-selected-facet-delete"></span>
   </li>
</script>