<script type="text/template" id="wizzy-facet-item-common">
    <li class="wizzy-facet-list-item {{#isSwatch}}facet-has-swatch{{/isSwatch}} {{#isSelected}}active{{/isSelected}}"
        data-key="{{ key }}" data-term="{{{ label }}}" title="{{{ label }}}">
      <span class="wizzy-facet-list-item-label">
        <span class="wizzy-facet-list-item-checkbox">
            <input type="checkbox" {{#isSelected}}checked{{/isSelected}} />
            <div class="checkbox-indicator"></div>
        </span>
         <?= $block->getReusableHTML('Wizzy_Search::common/swatch.phtml'); ?>
        <span class="facet-item-label-value">{{{ label }}}</span>
      </span>
      <span class="wizzy-facet-list-item-count">
       ({{ count }})
      </span>
   </li>
</script>