var config = {
    'paths': {
        'wizzy/bundle': 'Wizzy_Search/core/wizzyBundle.min',
        'Mustache': 'Wizzy_Search/lib/mustache.min',
        'noUiSlider': 'Wizzy_Search/lib/nouislider.min',
        'wNumb': 'Wizzy_Search/lib/wNumb.min',
        'wizzy/common' : 'Wizzy_Search/core/wizzyCommon',
        'wizzy/utils' : 'Wizzy_Search/core/wizzyUtils',
        'wizzy/utils/facets' : 'Wizzy_Search/core/wizzyFacetsUtils',
        'wizzy/utils/filters' : 'Wizzy_Search/core/wizzyFiltersUtils',
        'wizzy/libs/autocomplete': 'Wizzy_Search/lib/wizzyAutocomplete',
        'wizzy/libs/instantSearch': 'Wizzy_Search/lib/wizzyInstantSearch',
        'wizzy/libs/searchUrlUtils': 'Wizzy_Search/lib/wizzySearchUrlUtils',
        'wizzy/listeners/urlChange': 'Wizzy_Search/listeners/urlChangeListener',
        'wizzy/renderers/dom': 'Wizzy_Search/renderers/dom',
        'wizzy/renderers/autocomplete': 'Wizzy_Search/renderers/autocomplete',
        'wizzy/renderers/variation': 'Wizzy_Search/renderers/variation',
        'wizzy/renderers/wrapper': 'Wizzy_Search/renderers/wrapper',
        'wizzy/renderers/search': 'Wizzy_Search/renderers/search',
        'wizzy/fetchers/autocomplete': 'Wizzy_Search/fetchers/autocomplete',
        'wizzy/fetchers/filters': 'Wizzy_Search/fetchers/filters',
        'wizzy/fetchers/variation': 'Wizzy_Search/fetchers/variation',
        'wizzy/fetchers/search': 'Wizzy_Search/fetchers/search',
        'wizzy/libs/pageStore': 'Wizzy_Search/lib/wizzyPageStore',
        'wizzy/utils/keyboard': 'Wizzy_Search/utils/keyboard',
        'wizzy/utils/url': 'Wizzy_Search/utils/url',
        'wizzy/utils/search': 'Wizzy_Search/utils/search',
        'wizzy/utils/autocomplete': 'Wizzy_Search/utils/autocomplete',
        'wizzy/utils/pagination': 'Wizzy_Search/utils/pagination',
        'wizzy/renderers/components/search/summary': 'Wizzy_Search/renderers/components/search/summary',
        'wizzy/renderers/components/search/sort': 'Wizzy_Search/renderers/components/search/sort',
        'wizzy/renderers/components/search/results': 'Wizzy_Search/renderers/components/search/results',
        'wizzy/renderers/components/search/select': 'Wizzy_Search/renderers/components/search/select',
        'wizzy/renderers/components/search/products': 'Wizzy_Search/renderers/components/search/products',
        'wizzy/renderers/components/search/pagination': 'Wizzy_Search/renderers/components/search/pagination',
        'wizzy/renderers/components/filters/facets': 'Wizzy_Search/renderers/components/filters/facets',
        'wizzy/renderers/components/filters/selectedFacets': 'Wizzy_Search/renderers/components/filters/selectedFacets',
        'wizzy/renderers/components/filters/facetBlock': 'Wizzy_Search/renderers/components/filters/facetBlock',
        'wizzy/renderers/components/filters/common': 'Wizzy_Search/renderers/components/filters/common',
        'wizzy/renderers/components/filters/categories': 'Wizzy_Search/renderers/components/filters/categories',
        'wizzy/renderers/components/filters/commonRangeAbove': 'Wizzy_Search/renderers/components/filters/commonRangeAbove',
        'wizzy/renderers/components/filters/swatch': 'Wizzy_Search/renderers/components/filters/swatch',
        'wizzy/renderers/components/filters/range': 'Wizzy_Search/renderers/components/filters/range',
        'wizzy/analytics/clicks' : 'Wizzy_Search/analytics/clicks',
        'wizzy/analytics/views' : 'Wizzy_Search/analytics/views',
        'wizzy/analytics/sessions' : 'Wizzy_Search/analytics/sessions',
    }
};
