<div class="wizzy-progress-container {{#isForFilter}}{{^isPaginating}}for-filter{{/isPaginating}}{{/isForFilter}} {{#isPaginating}}for-pagination{{/isPaginating}}">
   <div class="wizzy-progress">
      <div class="wizzy-lds-ellipsis">
         <div></div>
         <div></div>
         <div></div>
         <div></div>
      </div><!-- ending of wizzy-lds-ellipsis -->
   </div><!-- ending of wizzy-progress -->
</div><!--ending of wizzy-progress-container -->
<div class="wizzy-progress-bg {{#isForFilter}}{{^isPaginating}}for-filter{{/isPaginating}}{{/isForFilter}} {{#isPaginating}}for-pagination{{/isPaginating}}"></div><!-- ending of wizzy-progress-bg -->