<?php
$configs = $block->getConfigs();
?>

{{#isSwatch}}
   <span class="wizzy-facet-item-swatch-wrapper {{#isVisualSwatch}}facet-visual-swatch{{/isVisualSwatch}}
       {{^isVisualSwatch}}facet-text-swatch{{/isVisualSwatch}}">
       <span class="wizzy-facet-item-swatch {{#isVisualSwatch}}facet-visual-swatch{{/isVisualSwatch}}
           {{^isVisualSwatch}}facet-text-swatch{{/isVisualSwatch}}"
             style="{{#isVisualSwatch}}{{#isURLSwatch}}background-image:url({{swatchValue}});{{/isURLSwatch}}
             {{^isURLSwatch}}background-color:{{swatchValue}};{{/isURLSwatch}}{{/isVisualSwatch}}">
           {{^isVisualSwatch}}
                {{#value}}
                    <span class="wizzy-facet-swatch-individual-value">{{value}}</span>
                {{/value}}
                {{#swatchValue}}
                    <span class="wizzy-facet-swatch-value">{{swatchValue}}</span>
                {{/swatchValue}}
           {{/isVisualSwatch}}
       </span>
   </span>
{{/isSwatch}}
