<?php
/** @var Wizzy\Search\Block\Adminhtml\System\Config\ResetConfigButton $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$storeViewId = $block->getStoreViewId();
$ajaxUrl = $block->escapeJs($block->getAjaxUrl());
$scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function ResetConfig() {
        new Ajax.Request('{$ajaxUrl}', {
            method: 'get',
            parameters: {store: '{$storeViewId}'},
            onSuccess: function(response) {
                window.location.reload();
            }
        });
    }
    window.ResetConfig = ResetConfig;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-reset-values">
    <p class="admin__field-error hidden" id="reset_values"></p>
    <button class="action-reset-values" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'ResetConfig();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
