<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>

<style>
    #<?= /* @noEscape */ $block->getConfigSelectorToHide(); ?> {
        display: none;
    }
</style>

<script type="text/javascript">
    (function  () {
        require(["jquery"], function($) {
            $(document).ready(function($) {
                window.location.href = '<?= /* @noEscape */ $block->getPageRedirectUrl(); ?>';
            });
        });
    })();
</script>
