<?php
/** @var $block \Magento\Framework\View\Element\Template */
$syncResults = $block->getSyncStatus();
foreach ($syncResults as $syncResult) { ?>
    <div class="admin__fieldset-wrapper-title">
        <p class="product-id"><?= "<b>Store ID</b> : ", $block->escapeHtml($syncResult['store_id']); ?></p>
        <span><?= $block->escapeHtml('Sync Status :'); ?></span>
        <?php
        if ($syncResult['status'] == 1 && !$syncResult['skipped_data']) { ?>
            <b><?= $block->escapeHtml('Synced'); ?></b>
            <?php
        } elseif ($syncResult['status'] == 0) { ?>
            <b><?= $block->escapeHtml('In sync'); ?></b>
            <?php
        } elseif ($syncResult['status'] == -1) { ?>
            <b><?= $block->escapeHtml('Product is not added in sync yet'); ?></b>
            <?php
        } elseif ($syncResult['skipped_data']) { ?>
            <b><?= $block->escapeHtml('Product Skipped during Sync'); ?></b>
            <div class="admin__fieldset-note admin__scope-old"></div>
            <span><?= $block->escapeHtml('Reason: '); ?></span>
            <b><?= $block->escapeHtml($syncResult['skipped_data']); ?></b>
        <?php } ?>
    </div>
    <div class="admin__fieldset-wrapper-title">
        <span><?= $block->escapeHtml('Last Updated At :'); ?></span>
        <b><?= $block->escapeHtml($syncResult['updated_at']); ?></b>
    </div>
    <br>
<?php } ?>