<?php

namespace Wizzy\Search\Block\Filters;

use Wizzy\Search\Block\BaseBlock;

class Facet extends BaseBlock {
   public function getConfigs() {
      return parent::getConfigs(); // TODO: Change the autogenerated stub
   }
}
