<?php

namespace Wizzy\Search\Block\Autocomplete;

use Wizzy\Search\Block\BaseBlock;

class Suggestion extends BaseBlock {
   public function getConfigs() {
      return parent::getConfigs(); // TODO: Change the autogenerated stub
   }
}
