<?php

namespace Wizzy\Search\Block\Core;

use Wizzy\Search\Block\BaseBlock;

class Config extends BaseBlock {
   public function getConfigs() {
      return parent::getConfigs(); // TODO: Change the autogenerated stub
   }
}
