<?php

namespace Wizzy\Search\Block\Search;

use Wizzy\Search\Block\BaseBlock;

class Sort extends BaseBlock {
   public function getConfigs() {
      return parent::getConfigs(); // TODO: Change the autogenerated stub
   }
}
